INSERT INTO people (name, age, job) VALUES
    ('Alice Smith', 28, 'Software Engineer'),
    ('Bob Johnson', 35, 'Product Manager'),
    ('Charlie Brown', 42, 'Designer'),
    ('Diana Prince', 31, 'DevOps Engineer'),
    ('Eve Martinez', 27, 'Data Scientist'),
    ('Frank Castle', 45, 'Security Architect'),
    ('Grace Hopper', 39, 'Backend Developer'),
    ('Henry Ford', 52, 'Engineering Manager'),
    ('Iris West', 29, 'Frontend Developer'),
    ('Jack Ryan', 33, 'Cloud Architect'),
    ('Kate Bishop', 26, 'QA Engineer'),
    ('Liam Neeson', 48, 'Solutions Architect'),
    ('Maya Lopez', 30, 'UX Designer'),
    ('Nathan Drake', 37, 'Full Stack Developer'),
    ('Olivia Pope', 41, 'Project Manager'),
    ('Peter Parker', 24, 'Junior Developer'),
    ('Quinn Fabray', 32, 'Technical Writer'),
    ('Rachel Green', 36, 'Business Analyst'),
    ('Steve Rogers', 40, 'Tech Lead'),
    ('Tina Turner', 44, 'Database Administrator');
